src/api/urls.py
# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: 2017 Rohit Lodha
# Copyright (c) 2017 Rohit Lodha
# SPDX-License-Identifier: Apache-2.0

from django.urls import path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from api import views

schema_view = get_schema_view(
   openapi.Info(
      title="API docs",
      default_version='v1',
      description="SPDX API API",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    path('validate/', views.validate, name='validate-api'),
    path('convert/', views.convert, name='convert-api'),
    path('compare/', views.compare, name='compare-api'),
    path('check_license/', views.check_license, name='check_license-api'),
    path('submit_license/', views.submit_license, name='submit_license-api'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui')
]

src/src/urls.py
# SPDX-FileCopyrightText: 2017 Rohit Lodha
# Copyright (c) 2017 Rohit Lodha
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""src URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include
from django.urls import path, re_path
from django.contrib import admin
from django.views.generic import RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from api import views


router = routers.DefaultRouter()
#router.register(r'users', views.UserViewSet)
#router.register(r'groups', views.GroupViewSet)
router.register(r'validate', views.ValidateViewSet)
router.register(r'convert', views.ConvertViewSet)
router.register(r'compare', views.CompareViewSet)

urlpatterns = [
	re_path(r'^(/)?$', RedirectView.as_view(url=settings.HOME_URL),name="root"),
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
    path('api/', include('api.urls')),
    path('api2/', include(router.urls)),
    path('api-auth/', include(("rest_framework.urls", 'api_auth'), namespace='rest_framework')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('auth/', include(("rest_framework_social_oauth2.urls", 'github_auth'), namespace='github_social')),
]

urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/app/forms.py
# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: 2017 Rohit Lodha
# Copyright (c) 2017 Rohit Lodha
# SPDX-License-Identifier: Apache-2.0

from django import forms
from django.contrib.auth.models import User

from app.models import UserID, LicenseNamespace, OrganisationName
from app.widgets import RelatedFieldWidgetCanAdd

OSI_CHOICES = (
    (0, "-"),
    ("Approved", "Approved"),
    ("Not Submitted", "Not Submitted"),
    ("Pending", "Submitted, but pending"),
    ("Rejected", "Rejected"),
    ("Unknown", "Don't know")
)

YES_NO_CHOICES = (
    (False, 'No'),
    (True, 'Yes'),
)

class TooltipTextInput(forms.TextInput):
    def __init__(self, tooltip='', attrs=None):
        super().__init__(attrs)
        self.tooltip = tooltip

    def get_context(self, name, value, attrs):
        context = super().get_context(name, value, attrs)
        context['widget']['attrs']['data-toggle'] = 'tooltip'
        context['widget']['attrs']['title'] = self.tooltip
        return context
    
class CustomSelectWidget(forms.Select):
    def __init__(self, *args, **kwargs):
        self.tooltip = kwargs.pop('tooltip', '')  # Get the tooltip text from widget attributes
        super().__init__(*args, **kwargs)

    def get_context(self, name, value, attrs):
        context = super().get_context(name, value, attrs)
        context['widget'].update({'attrs': {'title': self.tooltip}})  # Add the title attribute to the widget
        return context

class UserRegisterForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    def clean_username(self):
        users = self.cleaned_data["username"]
        if User.objects.filter(username=users).count() > 0:
            raise forms.ValidationError("This username already exists.")
        return users
    def clean(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password and password != confirm_password:
            raise forms.ValidationError("Passwords don't match.")
        return self.cleaned_data
    class Meta:
        model = User
        fields = ('first_name','last_name','email','username','password','confirm_password')

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserID
        fields = ('organisation',)

class InfoForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('first_name','last_name','email')

class OrgInfoForm(forms.ModelForm):

    class Meta:
        model = UserID
        fields = ('organisation',)

class LicenseRequestForm(forms.Form):

    def __init__(self, *args, **kwargs):
        if 'email' in kwargs:
            self.email = kwargs.pop('email')
        else:
            self.email = ""
        super(LicenseRequestForm, self).__init__(*args,**kwargs)
        self.fields["userEmail"] = forms.EmailField(label='Email', initial=self.email, max_length=35, required=False)

    licenseAuthorName = forms.CharField(label="License Author name", max_length=100, required=False, widget=TooltipTextInput(tooltip='License Author name goes here'))
    fullname = forms.CharField(label="Fullname", max_length=70, widget=TooltipTextInput(tooltip='Full Identifier of the license text goes here'))
    shortIdentifier = forms.CharField(label='Short identifier', max_length=50, widget=TooltipTextInput(tooltip='A short identifier of the license'))
    sourceUrl = forms.CharField(label='Source / URL', required=False, widget=TooltipTextInput(tooltip='Source URL for the license text'))
    osiApproved = forms.ChoiceField(
        choices=OSI_CHOICES,
        widget=CustomSelectWidget(tooltip='OSI status')
    )
    isException = forms.ChoiceField(
        choices=YES_NO_CHOICES,
        widget=CustomSelectWidget(tooltip='Whether or not the license is an exception')
    )
    exampleUrl = forms.CharField(label='Example Projects / URL', required=True, widget=TooltipTextInput(tooltip='Example project URL where the license is being used'))
    comments = forms.CharField(label='Comments', required=True, widget=forms.Textarea(attrs={'rows': 4, 'cols': 40}))
    licenseHeader = forms.CharField(label='Standard License Header', widget=forms.Textarea(attrs={'rows': 3, 'cols': 40}), required=False)
    text = forms.CharField(label='Text', widget=forms.Textarea(attrs={'rows': 4, 'cols': 40}))


class LicenseNamespaceRequestForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        if 'email' in kwargs:
            self.email = kwargs.pop('email')
        else:
            self.email = ""
        super(LicenseNamespaceRequestForm, self).__init__(*args, **kwargs)
        self.fields['shortIdentifier'].required = False
        self.fields['url'].required = True
        self.fields['license_list_url'].required = False
        self.fields['github_repo_url'].required = False
        self.fields['organisation'].required = False
        self.fields["userEmail"] = forms.EmailField(label='Email', initial=self.email, max_length=35, required=False)

    organisation = forms.ModelChoiceField(
       required=False,
       queryset=OrganisationName.objects.all(),
       widget=RelatedFieldWidgetCanAdd(OrganisationName))

    class Meta:
        model = LicenseNamespace
        fields = ('organisation', 'licenseAuthorName',
                  'fullname', 'userEmail', 'url',
                  'license_list_url', 'github_repo_url',
                  'publiclyShared', 'namespace',
                  'description', 'archive', 'shortIdentifier')

src/app/templates/app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="An easy all-in-one portal to upload and parse SPDX documents for validation, conformance check, comparison, conversion and SPDX License List search.">
    <meta name="keywords" content="SPDX, SBOM, validation, conformance, license, licence, compare, convert, SPDX License List, open source, free software, online tools, software bill of materials, supply chain security, NTIA, CISA, compliance">
    <meta name="author" content="SPDX">
    <link rel="icon" type="image/png" href="{% static 'img/spdx-icon.png' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <title >SPDX Online Tools {% block title %}{% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/starter-template.css' %}" rel="stylesheet" type="text/css">
    {% block head_block %}{% endblock %}
	</head>
<style>
.navbar-inverse {
    background-color: #0097c4;
    border-color: #0097c4;
}
.navbar-inverse .navbar-nav > li > a:hover, .navbar-inverse .navbar-nav > li > a:focus {
    color: #fff;
    background-color: transparent;
    border-bottom: 3px solid;
}
.navbar-inverse .navbar-nav > li > a {
    color: #fff;
}
.navbar-inverse .navbar-brand:hover, .navbar-inverse .navbar-brand:focus {
    color: black;
    background-color: transparent;
}
.navbar-inverse .navbar-brand {
    color: #fff;
}
.navbar-inverse .navbar-nav .linkactive {
    color: black;
    background-color: transparent;
    border-bottom: 3px solid;
}
.panel-default > .panel-heading {
    color: #333;
    background-color: #f5f5f5;
    border-color: #0097c4;
}
.panel-default {
    border-color: #0097c4;
}
.green-modal {
    background-color: #04dd2f;
}
.red-modal{
    background-color: #ea2300;
}
.yellow-modal{
    background-color: #ffcc00;
}
.dropdown-menu {
    font-size: 18px;
}
.dropdown-menu > li > a {
    color: #0097C4;
}
.left-align {
  text-align: left;
}
tbody tr {
  cursor: pointer;
}
th {
  text-align: center;
}
tbody tr:hover {
  background-color: #ddd!important;
}
tbody tr:hover > .sorting_1 {
  background-color: #ddd!important;
}
.ui-autocomplete {
  background: white;
}
.ui-menu .ui-menu-item{
  border-radius: 0px;
  border: 1px solid #dcdcdc;
}
.ui-state-active {
  background-color: gray;
  font-weight: bold;
  color:white;
}
.licenseField {
  float: left;
  margin-top: 1.5em;
}
.fieldName {
  font-size: 1.4em;
  color: #3197c4;
}
div p {
  text-align: left;
}
.lead {
  text-align: center;
}
.btn-info {
  background-color: #3197c4;
  border: none;
}
.btn-info:hover {
  background-color: RoyalBlue;
}
.btn-space {
  margin-right: 1em;
}
.error-log {
  font-size: 0.6em;
  text-align: left;
  white-space: pre-wrap;
}
</style>
  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand navbar-left" id="indexpage" href="/app/">SPDX Online Tools</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse" >
        <ul class="nav navbar-nav" style="font-size: 12px;">
            <li><a href="/app/about/" id="aboutpage">About</a></li>
            <li><a href="/app/validate/" id="validatepage">Validate</a></li>
            <li><a href="/app/compare/" id="comparepage">Compare</a></li>
            <li><a href="/app/convert/" id="convertpage">Convert</a></li>
            <li><a href="/app/check_license/" id="checklicensepage">License Check</a></li>
            <!-- <li><a href="/app/diff/" id="licensediffpage">License Diff</a></li> -->
            <li><a href="/app/xml_upload/" id="license-xml-editor">License XML Editor</a></li>
            <li><a href="/app/ntia_checker/" id="checkerpage">Conformance Checker</a></li>
            <li><a href="/app/dots/" id="dots">Visual Editor</a></li>
            <li>
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="licenserequest">License Requests
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" style="font-size: 12px;">
                <li><a href="/app/submit_new_license/" id="submitnewlicensepage">Submit New License</a></li>
                <li><a href="/app/license_requests/" id="licenserequestspage">License Requests</a></li>
                <li><a href="/app/archive_requests/" id="archiverequestspage">Archive Requests</a></li>
              </ul>
            </li>
            <!-- Remove the namespace menu until we decide on the specific functionality
			<li>
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="licensenamespace">License namespaces
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" style="font-size: 12px;">
                <li><a href="/app/submit_new_license_namespace/" id="submitnewlicensenamespacepage">Submit namespace</a></li>
                <li><a href="/app/license_namespace_requests/" id="licensenamespacerequests">License namespaces</a></li>
                <li><a href="/app/archive_namespace_requests/" id="archivenamespacerequestspage">Archived namespaces</a></li>
              </ul>
            </li> 
			-->
		  </ul>
		  <ul class="nav navbar-nav navbar-right" style="margin-right: 25px;font-size: 12px;">
        <div class="navbar-left" style="margin-top: 14px; ">
          <a href="https://spdx.dev/" id="spdxhome" target="_blank">
            <img class="starting-logo dark-version skip-lazy" width="80" height="20" alt="Software Package Data Exchange (SPDX)" src="{% static 'img/spdx-white.svg' %}">
          </a>
        </div>
        {% if user.is_authenticated %}
        <!--<li><a href="/app/profile/" id="profilepage">Profile</a></li>-->
        <li><a class="dropdown-toggle" data-toggle="dropdown" href="#">{{user}} <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/app/logout/"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
          </ul>
        </li>
        {% else %}
        <li><a href="/app/login/" id="loginpage"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        {% endif %}
      </ul>
    </div><!--/.nav-collapse -->
  </nav>

  <div class="container body1">

      <div class="starter-template">
        {% block body1 %}{% endblock %}
      </div>

    </div><!-- /.container -->
		{% block body2 %}{% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/warning.js' %}"></script>
    <script type="text/javascript">
      // Shift content down if the navbar gets taller,
      // so the navbar doesn't cover the content.
      // This workaround will work for desktop-size screen which is our main target.
      // Future design of template should better handle variable height of navbar.
      $(function() {
        function adjustContentPadding() {
          const navHeight = $('.navbar-fixed-top').height();
          const newPadding = navHeight + 10; // Add 10px for extra space
          $('body').css('padding-top', newPadding + 'px');
          var $dotsIframe = $('#dots-iframe');
          if ($dotsIframe.length) {
            $dotsIframe.css('height', 'calc(100vh - ' + newPadding + 'px)');
            $dotsIframe.css('min-height', 'calc(100vh - ' + newPadding + 'px)');
            $dotsIframe.css('margin-top', newPadding + 'px');
          }
        }
        // Adjust on load and resize
        $(window).on("load resize", adjustContentPadding);
      });
    </script>
    {% block script_block %}{% endblock %}
  </body>
</html>

src/app/templates/app/check_license.html
{% extends 'app/base.html' %}
{% load static %}
{% block body1 %}
<div id="messages" class="messages">
</div>
<p class="lead">{{ error }}</p>
<div class="panel panel-default">
  <div class="panel-heading">
    <p class="lead">Check license</p>
  </div>
  <div class="panel-body" style="overflow:scroll;">
    <form id="checklicenseform" enctype="multipart/form-data" class="form-horizontal" method="post">
      {% csrf_token %}
      <p>Enter full license text in the text area below to check it against 
      <a href="https://spdx.org/licenses/">SPDX License List</a> and
      <a href="https://spdx.org/licenses/exceptions-index.html">License Exceptions</a>.</p>
      <p>The result of the compare would be one of "Exact match", "Close match" or "No match".</p>
      <textarea id="licensetext" name="licensetext" rows="18" style="width: 100%"></textarea>
      <button id="checklicensebutton" class=" btn btn-md btn-info" type="submit">Check license</button>
    </form>
    {% include "app/modal.html" %}
  </div>
</div>
{% endblock %}
{% block script_block %}
<script type="text/javascript">
$(document).ready(function () {
    $("#checklicensepage").addClass('linkactive');
    });
</script>
<script type="text/javascript">
function checkform() {
  if ($('#licensetext').val() == "") {
    $('#licensetext').focus();
    return ("No text entered.");
  }
  else {
    return "1";
  }
}
</script>
<script type="text/javascript">
  $('#checklicenseform').on('submit', function(event){
    event.preventDefault();
    var check = checkform();
    if (check=="1"){
      $("#checklicensebutton").text("Checking...");
      $("#checklicensebutton").prop('disabled', true);
      $("#messages").html("");
      var form = new FormData($("#checklicenseform")[0]);
      $.ajax({
              type: "POST",
              enctype: 'multipart/form-data',
              url: "/app/check_license/",
              processData: false,
              contentType: false,
              cache: false,
              dataType: 'json',
              data: form,
              success: function (data) {
                  console.log("SUCCESS : ", data);
				  $("#modal-header").removeClass("red-modal");
				  if (data["data"].toLowerCase().indexOf("perfect match") > -1 || data["data"].toLowerCase().indexOf("exact match") > -1) {
                     $("#modal-header").addClass("green-modal");
				  } else {
				     $("#modal-header").addClass("yellow-modal");
				  }
                  $("#modal-title").html("Success!");
                  $("#modal-body").html("<h3>"+data.data+"</h3>");
                  $("#myModal").modal({
                          backdrop: 'static',
                          keyboard: true, 
                          show: true
                  });
                  $("#checklicensebutton").text("Check license");
                  $("#checklicensebutton").prop('disabled', false);
              },
              error: function (e) {
                  console.log("ERROR : ", e);
                  $("#modal-header").removeClass("green-modal");
                  try {
                    var obj = JSON.parse(e.responseText);
                    $("#modal-header").addClass("red-modal");
                    $("#modal-title").html("Error!");
                    $("#modal-body").text(obj.data);
                  }
                  catch (e){
                    $("#modal-header").addClass("red-modal");
                    $("#modal-title").html("Error!");
                    $("#modal-body").text("The application could not be connected. Please try later.");
                  }
                  $("#myModal").modal({
                          backdrop: 'static',
                          keyboard: true, 
                          show: true
                  });
                  $("#checklicensebutton").text("Check license");
                  $("#checklicensebutton").prop('disabled', false);
              }
          });
    }
    else{
      $("#messages").html('<div class="alert alert-danger alert-dismissable fade in"><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a><strong>Error!</strong> '+check+'</div>');
      setTimeout(function() {
        $("#messages").html("");
      }, 5000);
    }
});

</script>
{% endblock %}

src/app/templates/app/index.html
{% extends 'app/base.html' %}
{% load static %}
{% block body1 %}
<div class="container">
    <div class="row text-center">
        <div class="col-sm-12">
            <img src="{% static 'img/spdx.png' %}" alt="SPDX logo" class="img-responsive center-block" />
        </div>
    </div>
    <div class="row text-center">
        <div class="col-sm-12">
            <p class="lead" style="color:#0097c4;">
                <strong>SPDX Online Tools -
                    an all-in-one portal to upload and parse SPDX documents
                    for validation, conformance check, comparison, conversion
                    and SPDX License List search.</strong>
            </p>
            <p class="lead">Select the tool by clicking on the tool name on
                the menu bar.</p>
        </div>
    </div>
</div>
{% endblock %}

src/app/templates/app/modal.html
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog" style="width: 70rem;">

    <!-- Modal content-->
    <div class="modal-content">
      <div id="modal-header" class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 id="modal-title" class="modal-title"></h4>
      </div>
       <div id="modal-body" class="modal-body" style="font-size:24px;">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

src/app/templates/app/register.html
{% extends 'app/base.html' %}
{% load static %}
{% block body1 %}
<div id="messages" class="messages">
</div>
<p class ="lead"> {{ error1 }}</p>
<p class ="lead"> {{ error2 }}</p>
<div class="col-md-3">
</div>
<div class="col-md-6">
<div class="panel panel-default">
<div class="panel-heading"><p class="lead">Join the community</p></div>
<div class="panel-body">
<p class="lead" style="color:red;">{{ invalid }}</p>
    <form id="register_form" role="form"  class="form-horizontal"  method="post" action="/app/register/" enctype="multipart/form-data" onsubmit="return checkForm()">
        {% csrf_token %}
        {% for field in user_form %}
        <div class="form-group">
      	<label class="control-label col-sm-4" >{{ field.label_tag }}</label>
    	      	<div class="col-sm-5">
          		  {{ field }}
          		</div>
              <div class="col-sm-3">
              </div>
      	</div>
	      {% endfor %}
      	{% for field in profile_form %}
      	<div class="form-group">
      	<div class="text-danger">{{ field.errors }}</div>
           	 <label class="control-label col-sm-4" >{{ field.label_tag }}</label>
      	      	<div class="col-sm-5">
            		{{ field }}
            		</div>
                <div class="col-sm-3">
                </div>
      	</div>
		    {% endfor %}
        <div class="form-group">
          <div class="col-sm-offset-4 col-sm-5">
            <button type="submit" class="btn btn-lg btn-block btn-info"><span class="glyphicon glyphicon-ok"></span> Create Account</button>
          </div>
        </div>
    </form> 
    <h5><a href="{% url 'social:begin' 'github' %}?next=/app">Login with GitHub</a></h5>
    <h5><a href="/app/login/">Already a user?</a></h5>
</div>
</div>
</div>
<div class="col-md-3">
</div>
{% endblock %}
{% block script_block %}
<script type="text/javascript">
$(document).ready(function () {
    $("#registerpage").addClass('linkactive');
  });
</script>
<script type="text/javascript">
function validateEmail(email) {
  var re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
  return re.test(email);
}
function validateUserName(username){
  var form = new FormData();
  var result = false;
  form.append("username",username);
  form.append("csrfmiddlewaretoken",document.getElementsByName('csrfmiddlewaretoken')[0].value);
  $.ajax({
            type: "POST",
            enctype: 'multipart/form-data',
            url: "/app/checkusername/",
            processData: false,
            contentType: false,
            cache: false,
            dataType: 'json',
            timeout: 600000,
            data: form,
            async: false,
            success: function (data) {
              //console.log("Username does not exist");
              result = true;
            },
            error: function (e) {
              //console.log("Username exist");
              result = false;
            }
        });
    return result;
}
function validateForm() {
    var letters = /^[A-Za-z ]+$/;
    var firstname = $("#id_first_name").val();
    if (firstname){
      if (firstname.match(letters)){
      }
      else{
        return "Enter a valid first name.";
      }
    }
    else {
      return "Enter a valid first name.";
    }
    var lastname = $("#id_last_name").val()
    if (lastname){
      if (lastname.match(letters)){
      }
      else{
        return "Enter a valid last name.";
      }
    }
    else {
      return "Enter a valid last name.";
    }
    var email = $("#id_email").val();
    if (validateEmail(email)) {
    }
    else {
      return "Enter a valid email address.";
    }
    var username = $("#id_username").val();
    var checkuser = validateUserName(username);
    if (checkuser==true){
    }
    else{
      return "Username already exists."
    }
    var organisation = $("#id_organisation").val();
    if (organisation){
    }
    else {
      return "Enter a valid organisation name.";
    }
    return "1";
}
function checkForm() {
  var check = validateForm();
  if (check=="1"){
    return true;
  }
  else{
      $("#messages").html('<div class="alert alert-danger alert-dismissable fade in"><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a><strong>Error! </strong>'+check+'</div>');
      setTimeout(function() {
        $("#messages").html("");
      }, 5000);
      return false;
    }
}
</script>
{% endblock %}

src/app/templates/app/search.html
{% extends 'app/base.html' %}
{% load static %}
{% load staticfiles %}
{% block body1 %}
<p class="lead" style="color:blue;">Search</p>
<hr>
<p class="lead">This is the search page</p>
{% endblock %}
{% block script_block %}
<script type="text/javascript">
$(document).ready(function () {
    $("#searchpage").addClass('linkactive');
    });
</script>
{% endblock %}